/**
 * Design tokens for the Mimo Pet Spa landing page.
 * Ported from the Stitch export so class names in the components stay 1:1
 * with the original markup (e.g. `bg-primary-container`, `text-display-lg`,
 * `font-headline-lg`, `p-space-xl`).
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#201b16',
        'primary-container': '#e8927c',
        'on-tertiary-fixed': '#1d1b16',
        'surface-container-high': '#f1e6df',
        'on-primary-fixed': '#3a0a01',
        tertiary: '#615e57',
        'surface-dim': '#e3d8d1',
        'surface-container-low': '#fdf2ea',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        background: '#fff8f4',
        'inverse-surface': '#352f2a',
        'inverse-primary': '#ffb4a2',
        'on-error-container': '#93000a',
        'tertiary-container': '#ada8a0',
        'on-tertiary-fixed-variant': '#494640',
        'surface-variant': '#ebe0d9',
        'primary-fixed': '#ffdbd2',
        'on-primary-fixed-variant': '#733424',
        secondary: '#3e6750',
        'on-tertiary-container': '#403d37',
        'surface-tint': '#904b39',
        'surface-bright': '#fff8f4',
        'on-error': '#ffffff',
        'outline-variant': '#d9c1bc',
        'on-surface-variant': '#54433f',
        error: '#ba1a1a',
        'secondary-fixed': '#c0edd0',
        outline: '#86736e',
        surface: '#fff8f4',
        'on-secondary-fixed-variant': '#264f39',
        'secondary-container': '#bdeacd',
        'tertiary-fixed-dim': '#cbc6bd',
        'primary-fixed-dim': '#ffb4a2',
        'on-secondary-container': '#426b54',
        'error-container': '#ffdad6',
        'surface-container': '#f7ece4',
        'surface-container-highest': '#ebe0d9',
        'tertiary-fixed': '#e7e2d9',
        'secondary-fixed-dim': '#a4d1b5',
        primary: '#904b39',
        'inverse-on-surface': '#faefe7',
        'on-primary-container': '#672b1b',
        'on-background': '#201b16',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#002112',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1.25rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
      },
      fontFamily: {
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'title-md': ['17px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
